-- V1 initial schema.
--
-- Follows desgin/"E-Learning Platform — V1 Backend Data Model.md".
-- Conventions:
--   * uuid primary keys, generated by the database (gen_random_uuid, core since PG13)
--   * timestamptz everywhere; the application works in UTC
--   * enums as varchar + CHECK rather than native PG enum types, so adding a
--     value is an ordinary migration instead of an ALTER TYPE dance
--   * every foreign key used for lookups is indexed
--   * ON DELETE CASCADE only where the child cannot exist without the parent

-- ============================================================================
-- Platform: media
-- ============================================================================

CREATE TABLE media_objects (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    bucket             varchar(63)  NOT NULL,
    object_key         varchar(1024) NOT NULL,
    original_filename  varchar(512),
    mime_type          varchar(255) NOT NULL,
    size_bytes         bigint       NOT NULL CHECK (size_bytes >= 0),
    checksum           varchar(128),
    status             varchar(32)  NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'AVAILABLE', 'FAILED', 'DELETED')),
    created_at         timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT uq_media_objects_location UNIQUE (bucket, object_key)
);

-- ============================================================================
-- Identity
-- ============================================================================

CREATE TABLE users (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email         varchar(320) NOT NULL,
    username      varchar(64)  NOT NULL,
    password_hash varchar(255) NOT NULL,
    status        varchar(32)  NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DISABLED', 'PENDING')),
    created_at    timestamptz  NOT NULL DEFAULT now(),
    updated_at    timestamptz  NOT NULL DEFAULT now(),
    last_login_at timestamptz,
    CONSTRAINT uq_users_email    UNIQUE (email),
    CONSTRAINT uq_users_username UNIQUE (username)
);

CREATE TABLE user_profiles (
    user_id         uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    first_name      varchar(100),
    last_name       varchar(100),
    bio             text,
    avatar_media_id uuid REFERENCES media_objects (id) ON DELETE SET NULL,
    timezone        varchar(64)  NOT NULL DEFAULT 'UTC',
    language        varchar(16)  NOT NULL DEFAULT 'en'
);

CREATE INDEX idx_user_profiles_avatar ON user_profiles (avatar_media_id);

-- ============================================================================
-- Classification: categories and tags
-- ============================================================================

CREATE TABLE categories (
    id        uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_id uuid REFERENCES categories (id) ON DELETE CASCADE,
    name      varchar(160) NOT NULL,
    slug      varchar(160) NOT NULL,
    CONSTRAINT uq_categories_slug UNIQUE (slug)
);

CREATE INDEX idx_categories_parent ON categories (parent_id);

CREATE TABLE tags (
    id   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name varchar(80) NOT NULL,
    slug varchar(80) NOT NULL,
    CONSTRAINT uq_tags_slug UNIQUE (slug)
);

-- ============================================================================
-- Course management
-- ============================================================================

CREATE TABLE courses (
    id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id            uuid NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    title               varchar(255) NOT NULL,
    slug                varchar(255) NOT NULL,
    description         text,
    short_description   varchar(500),
    status              varchar(32)  NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
    level               varchar(32)  NOT NULL DEFAULT 'ALL_LEVELS'
        CHECK (level IN ('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'ALL_LEVELS')),
    language            varchar(16)  NOT NULL DEFAULT 'en',
    thumbnail_media_id  uuid REFERENCES media_objects (id) ON DELETE SET NULL,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    updated_at          timestamptz  NOT NULL DEFAULT now(),
    published_at        timestamptz,
    CONSTRAINT uq_courses_slug UNIQUE (slug)
);

CREATE INDEX idx_courses_owner  ON courses (owner_id);
CREATE INDEX idx_courses_status ON courses (status);

-- Course search starts in PostgreSQL (Stack.md). A generated tsvector keeps the
-- index in sync without application code or triggers.
ALTER TABLE courses
    ADD COLUMN search_vector tsvector
    GENERATED ALWAYS AS (
        setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('simple', coalesce(short_description, '')), 'B') ||
        setweight(to_tsvector('simple', coalesce(description, '')), 'C')
    ) STORED;

CREATE INDEX idx_courses_search ON courses USING gin (search_vector);

CREATE TABLE course_instructors (
    course_id     uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    instructor_id uuid NOT NULL REFERENCES users (id)   ON DELETE CASCADE,
    role          varchar(32) NOT NULL DEFAULT 'ASSISTANT'
        CHECK (role IN ('PRIMARY', 'ASSISTANT', 'GUEST')),
    PRIMARY KEY (course_id, instructor_id)
);

CREATE INDEX idx_course_instructors_instructor ON course_instructors (instructor_id);

CREATE TABLE course_sections (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id   uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    title       varchar(255) NOT NULL,
    description text,
    position    integer NOT NULL CHECK (position >= 0),
    CONSTRAINT uq_course_sections_position UNIQUE (course_id, position) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_course_sections_course ON course_sections (course_id);

CREATE TABLE course_items (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    section_id     uuid NOT NULL REFERENCES course_sections (id) ON DELETE CASCADE,
    title          varchar(255) NOT NULL,
    type           varchar(32)  NOT NULL
        CHECK (type IN ('LESSON', 'QUIZ', 'ASSIGNMENT')),
    position       integer NOT NULL CHECK (position >= 0),
    is_required    boolean NOT NULL DEFAULT true,
    available_from timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_items_position UNIQUE (section_id, position) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_course_items_section ON course_items (section_id);

CREATE TABLE course_categories (
    course_id   uuid NOT NULL REFERENCES courses (id)    ON DELETE CASCADE,
    category_id uuid NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    PRIMARY KEY (course_id, category_id)
);

CREATE INDEX idx_course_categories_category ON course_categories (category_id);

CREATE TABLE course_tags (
    course_id uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    tag_id    uuid NOT NULL REFERENCES tags (id)    ON DELETE CASCADE,
    PRIMARY KEY (course_id, tag_id)
);

CREATE INDEX idx_course_tags_tag ON course_tags (tag_id);

CREATE TABLE course_prerequisites (
    course_id              uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    prerequisite_course_id uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    PRIMARY KEY (course_id, prerequisite_course_id),
    CONSTRAINT ck_course_prerequisites_not_self CHECK (course_id <> prerequisite_course_id)
);

CREATE INDEX idx_course_prerequisites_prerequisite ON course_prerequisites (prerequisite_course_id);

CREATE TABLE item_prerequisites (
    item_id              uuid NOT NULL REFERENCES course_items (id) ON DELETE CASCADE,
    prerequisite_item_id uuid NOT NULL REFERENCES course_items (id) ON DELETE CASCADE,
    PRIMARY KEY (item_id, prerequisite_item_id),
    CONSTRAINT ck_item_prerequisites_not_self CHECK (item_id <> prerequisite_item_id)
);

CREATE INDEX idx_item_prerequisites_prerequisite ON item_prerequisites (prerequisite_item_id);

-- ============================================================================
-- Learning content: lessons
-- ============================================================================

CREATE TABLE lessons (
    course_item_id   uuid PRIMARY KEY REFERENCES course_items (id) ON DELETE CASCADE,
    content_type     varchar(32) NOT NULL
        CHECK (content_type IN ('VIDEO', 'ARTICLE', 'DOCUMENT', 'AUDIO', 'EXTERNAL')),
    description      text,
    duration_seconds integer CHECK (duration_seconds >= 0),
    completion_rule  varchar(32) NOT NULL DEFAULT 'MANUAL'
        CHECK (completion_rule IN ('MANUAL', 'VIEW', 'PERCENTAGE', 'DURATION'))
);

CREATE TABLE video_contents (
    lesson_id             uuid PRIMARY KEY REFERENCES lessons (course_item_id) ON DELETE CASCADE,
    media_id              uuid REFERENCES media_objects (id) ON DELETE SET NULL,
    thumbnail_media_id    uuid REFERENCES media_objects (id) ON DELETE SET NULL,
    hls_manifest_media_id uuid REFERENCES media_objects (id) ON DELETE SET NULL,
    duration_seconds      integer CHECK (duration_seconds >= 0)
);

CREATE INDEX idx_video_contents_media ON video_contents (media_id);

CREATE TABLE article_contents (
    lesson_id uuid PRIMARY KEY REFERENCES lessons (course_item_id) ON DELETE CASCADE,
    content   text NOT NULL
);

CREATE TABLE document_contents (
    lesson_id uuid PRIMARY KEY REFERENCES lessons (course_item_id) ON DELETE CASCADE,
    media_id  uuid REFERENCES media_objects (id) ON DELETE SET NULL
);

CREATE INDEX idx_document_contents_media ON document_contents (media_id);

-- ============================================================================
-- Assessment: quizzes
-- ============================================================================

CREATE TABLE quizzes (
    course_item_id      uuid PRIMARY KEY REFERENCES course_items (id) ON DELETE CASCADE,
    title               varchar(255) NOT NULL,
    instructions        text,
    passing_score       numeric(5, 2) CHECK (passing_score >= 0 AND passing_score <= 100),
    max_attempts        integer CHECK (max_attempts > 0),
    time_limit_seconds  integer CHECK (time_limit_seconds > 0),
    randomize_questions boolean NOT NULL DEFAULT false
);

CREATE TABLE questions (
    id       uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quiz_id  uuid NOT NULL REFERENCES quizzes (course_item_id) ON DELETE CASCADE,
    type     varchar(32) NOT NULL
        CHECK (type IN ('SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_TEXT', 'LONG_TEXT')),
    text     text NOT NULL,
    points   numeric(6, 2) NOT NULL DEFAULT 1 CHECK (points >= 0),
    position integer NOT NULL CHECK (position >= 0),
    CONSTRAINT uq_questions_position UNIQUE (quiz_id, position) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_questions_quiz ON questions (quiz_id);

CREATE TABLE question_options (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id uuid NOT NULL REFERENCES questions (id) ON DELETE CASCADE,
    text        text NOT NULL,
    is_correct  boolean NOT NULL DEFAULT false,
    position    integer NOT NULL CHECK (position >= 0),
    CONSTRAINT uq_question_options_position UNIQUE (question_id, position) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_question_options_question ON question_options (question_id);

CREATE TABLE quiz_attempts (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quiz_id        uuid NOT NULL REFERENCES quizzes (course_item_id) ON DELETE CASCADE,
    student_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    attempt_number integer NOT NULL CHECK (attempt_number > 0),
    status         varchar(32) NOT NULL DEFAULT 'IN_PROGRESS'
        CHECK (status IN ('IN_PROGRESS', 'SUBMITTED', 'GRADED', 'ABANDONED', 'EXPIRED')),
    score          numeric(6, 2) CHECK (score >= 0),
    started_at     timestamptz NOT NULL DEFAULT now(),
    submitted_at   timestamptz,
    graded_at      timestamptz,
    CONSTRAINT uq_quiz_attempts_number UNIQUE (quiz_id, student_id, attempt_number)
);

CREATE INDEX idx_quiz_attempts_student ON quiz_attempts (student_id);
CREATE INDEX idx_quiz_attempts_quiz    ON quiz_attempts (quiz_id);

CREATE TABLE quiz_responses (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    attempt_id         uuid NOT NULL REFERENCES quiz_attempts (id) ON DELETE CASCADE,
    question_id        uuid NOT NULL REFERENCES questions (id) ON DELETE CASCADE,
    selected_option_id uuid REFERENCES question_options (id) ON DELETE SET NULL,
    answer_text        text,
    is_correct         boolean,
    points_awarded     numeric(6, 2) CHECK (points_awarded >= 0)
);

CREATE INDEX idx_quiz_responses_attempt  ON quiz_responses (attempt_id);
CREATE INDEX idx_quiz_responses_question ON quiz_responses (question_id);

-- ============================================================================
-- Assessment: assignments
-- ============================================================================

CREATE TABLE assignments (
    course_item_id        uuid PRIMARY KEY REFERENCES course_items (id) ON DELETE CASCADE,
    instructions          text,
    max_score             numeric(6, 2) NOT NULL DEFAULT 100 CHECK (max_score > 0),
    due_at                timestamptz,
    allow_late_submission boolean NOT NULL DEFAULT false
);

CREATE TABLE assignment_submissions (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    assignment_id  uuid NOT NULL REFERENCES assignments (course_item_id) ON DELETE CASCADE,
    student_id     uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    attempt_number integer NOT NULL DEFAULT 1 CHECK (attempt_number > 0),
    status         varchar(32) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'SUBMITTED', 'GRADING', 'GRADED', 'RETURNED')),
    content        text,
    score          numeric(6, 2) CHECK (score >= 0),
    feedback       text,
    submitted_at   timestamptz,
    graded_at      timestamptz,
    graded_by      uuid REFERENCES users (id) ON DELETE SET NULL,
    CONSTRAINT uq_assignment_submissions_attempt UNIQUE (assignment_id, student_id, attempt_number)
);

CREATE INDEX idx_assignment_submissions_student   ON assignment_submissions (student_id);
CREATE INDEX idx_assignment_submissions_assignment ON assignment_submissions (assignment_id);

CREATE TABLE submission_media (
    submission_id uuid NOT NULL REFERENCES assignment_submissions (id) ON DELETE CASCADE,
    media_id      uuid NOT NULL REFERENCES media_objects (id) ON DELETE CASCADE,
    PRIMARY KEY (submission_id, media_id)
);

CREATE INDEX idx_submission_media_media ON submission_media (media_id);

-- ============================================================================
-- Student activity
-- ============================================================================

CREATE TABLE enrollments (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id   uuid NOT NULL REFERENCES users (id)   ON DELETE CASCADE,
    course_id    uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    status       varchar(32) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SUSPENDED')),
    enrolled_at  timestamptz NOT NULL DEFAULT now(),
    started_at   timestamptz,
    completed_at timestamptz,
    expires_at   timestamptz,
    CONSTRAINT uq_enrollments_student_course UNIQUE (student_id, course_id)
);

CREATE INDEX idx_enrollments_course  ON enrollments (course_id);
CREATE INDEX idx_enrollments_student ON enrollments (student_id);

CREATE TABLE learning_progress (
    id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id            uuid NOT NULL REFERENCES users (id)        ON DELETE CASCADE,
    course_id             uuid NOT NULL REFERENCES courses (id)      ON DELETE CASCADE,
    course_item_id        uuid NOT NULL REFERENCES course_items (id) ON DELETE CASCADE,
    status                varchar(32) NOT NULL DEFAULT 'NOT_STARTED'
        CHECK (status IN ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED')),
    progress_percent      numeric(5, 2) NOT NULL DEFAULT 0
        CHECK (progress_percent >= 0 AND progress_percent <= 100),
    last_position_seconds integer CHECK (last_position_seconds >= 0),
    started_at            timestamptz,
    completed_at          timestamptz,
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_learning_progress_student_item UNIQUE (student_id, course_item_id)
);

CREATE INDEX idx_learning_progress_course  ON learning_progress (course_id);
CREATE INDEX idx_learning_progress_student ON learning_progress (student_id);

CREATE TABLE certificates (
    id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    student_id         uuid NOT NULL REFERENCES users (id)   ON DELETE CASCADE,
    course_id          uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    media_id           uuid REFERENCES media_objects (id) ON DELETE SET NULL,
    certificate_number varchar(64) NOT NULL,
    verification_code  varchar(64) NOT NULL,
    issued_at          timestamptz NOT NULL DEFAULT now(),
    revoked_at         timestamptz,
    CONSTRAINT uq_certificates_number            UNIQUE (certificate_number),
    CONSTRAINT uq_certificates_verification_code UNIQUE (verification_code)
);

CREATE INDEX idx_certificates_student ON certificates (student_id);
CREATE INDEX idx_certificates_course  ON certificates (course_id);

-- ============================================================================
-- Resources
-- ============================================================================

CREATE TABLE resources (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title         varchar(255) NOT NULL,
    description   text,
    resource_type varchar(32) NOT NULL
        CHECK (resource_type IN ('DOCUMENT', 'SOURCE_CODE', 'VIDEO', 'AUDIO', 'IMAGE', 'LINK', 'OTHER')),
    source_type   varchar(32) NOT NULL
        CHECK (source_type IN ('FILE', 'URL', 'INLINE')),
    created_by    uuid REFERENCES users (id) ON DELETE SET NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_resources_created_by ON resources (created_by);

CREATE TABLE resource_files (
    resource_id uuid PRIMARY KEY REFERENCES resources (id) ON DELETE CASCADE,
    media_id    uuid NOT NULL REFERENCES media_objects (id) ON DELETE RESTRICT,
    filename    varchar(512),
    mime_type   varchar(255),
    extension   varchar(32),
    size_bytes  bigint CHECK (size_bytes >= 0)
);

CREATE INDEX idx_resource_files_media ON resource_files (media_id);

CREATE TABLE resource_urls (
    resource_id uuid PRIMARY KEY REFERENCES resources (id) ON DELETE CASCADE,
    url         varchar(2048) NOT NULL
);

CREATE TABLE resource_contents (
    resource_id  uuid PRIMARY KEY REFERENCES resources (id) ON DELETE CASCADE,
    content_type varchar(32) NOT NULL
        CHECK (content_type IN ('MARKDOWN', 'HTML', 'PLAIN_TEXT')),
    content      text NOT NULL
);

-- relationship_type is shared by the three scope tables below.
CREATE TABLE course_resources (
    course_id         uuid NOT NULL REFERENCES courses (id)   ON DELETE CASCADE,
    resource_id       uuid NOT NULL REFERENCES resources (id) ON DELETE CASCADE,
    relationship_type varchar(32) NOT NULL DEFAULT 'RESOURCE'
        CHECK (relationship_type IN ('RESOURCE', 'REFERENCE', 'ATTACHMENT', 'SUPPLEMENTARY',
                                     'REQUIRED', 'SOLUTION', 'EXAMPLE', 'READING')),
    position          integer NOT NULL DEFAULT 0 CHECK (position >= 0),
    PRIMARY KEY (course_id, resource_id)
);

CREATE INDEX idx_course_resources_resource ON course_resources (resource_id);

CREATE TABLE section_resources (
    section_id        uuid NOT NULL REFERENCES course_sections (id) ON DELETE CASCADE,
    resource_id       uuid NOT NULL REFERENCES resources (id)       ON DELETE CASCADE,
    relationship_type varchar(32) NOT NULL DEFAULT 'RESOURCE'
        CHECK (relationship_type IN ('RESOURCE', 'REFERENCE', 'ATTACHMENT', 'SUPPLEMENTARY',
                                     'REQUIRED', 'SOLUTION', 'EXAMPLE', 'READING')),
    position          integer NOT NULL DEFAULT 0 CHECK (position >= 0),
    PRIMARY KEY (section_id, resource_id)
);

CREATE INDEX idx_section_resources_resource ON section_resources (resource_id);

CREATE TABLE item_resources (
    course_item_id    uuid NOT NULL REFERENCES course_items (id) ON DELETE CASCADE,
    resource_id       uuid NOT NULL REFERENCES resources (id)    ON DELETE CASCADE,
    relationship_type varchar(32) NOT NULL DEFAULT 'RESOURCE'
        CHECK (relationship_type IN ('RESOURCE', 'REFERENCE', 'ATTACHMENT', 'SUPPLEMENTARY',
                                     'REQUIRED', 'SOLUTION', 'EXAMPLE', 'READING')),
    position          integer NOT NULL DEFAULT 0 CHECK (position >= 0),
    PRIMARY KEY (course_item_id, resource_id)
);

CREATE INDEX idx_item_resources_resource ON item_resources (resource_id);

-- ============================================================================
-- Community
-- ============================================================================

CREATE TABLE discussion_threads (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id  uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    -- nullable: a thread is either course-wide or attached to one lesson
    lesson_id  uuid REFERENCES lessons (course_item_id) ON DELETE CASCADE,
    author_id  uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title      varchar(255) NOT NULL,
    body       text,
    status     varchar(32) NOT NULL DEFAULT 'OPEN'
        CHECK (status IN ('OPEN', 'ANSWERED', 'CLOSED', 'HIDDEN')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_discussion_threads_course ON discussion_threads (course_id);
CREATE INDEX idx_discussion_threads_lesson ON discussion_threads (lesson_id);
CREATE INDEX idx_discussion_threads_author ON discussion_threads (author_id);

CREATE TABLE discussion_comments (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    thread_id  uuid NOT NULL REFERENCES discussion_threads (id) ON DELETE CASCADE,
    author_id  uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parent_id  uuid REFERENCES discussion_comments (id) ON DELETE CASCADE,
    body       text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_discussion_comments_thread ON discussion_comments (thread_id);
CREATE INDEX idx_discussion_comments_parent ON discussion_comments (parent_id);

CREATE TABLE course_reviews (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    course_id  uuid NOT NULL REFERENCES courses (id) ON DELETE CASCADE,
    student_id uuid NOT NULL REFERENCES users (id)   ON DELETE CASCADE,
    rating     smallint NOT NULL CHECK (rating BETWEEN 1 AND 5),
    title      varchar(255),
    body       text,
    status     varchar(32) NOT NULL DEFAULT 'PUBLISHED'
        CHECK (status IN ('PUBLISHED', 'PENDING', 'HIDDEN', 'REMOVED')),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_reviews_course_student UNIQUE (course_id, student_id)
);

CREATE INDEX idx_course_reviews_course ON course_reviews (course_id);

-- ============================================================================
-- Platform: notifications
-- ============================================================================

CREATE TABLE notifications (
    id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       varchar(64) NOT NULL,
    title      varchar(255) NOT NULL,
    body       text,
    -- contextual payload, so new notification types need no schema change
    data       jsonb NOT NULL DEFAULT '{}'::jsonb,
    read_at    timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Drives the "my unread notifications" query.
CREATE INDEX idx_notifications_user_unread ON notifications (user_id, created_at DESC)
    WHERE read_at IS NULL;
CREATE INDEX idx_notifications_data ON notifications USING gin (data);

CREATE TABLE notification_deliveries (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    notification_id uuid NOT NULL REFERENCES notifications (id) ON DELETE CASCADE,
    channel         varchar(32) NOT NULL
        CHECK (channel IN ('IN_APP', 'EMAIL', 'PUSH')),
    status          varchar(32) NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'SKIPPED')),
    sent_at         timestamptz,
    failure_reason  text,
    CONSTRAINT uq_notification_deliveries_channel UNIQUE (notification_id, channel)
);

CREATE INDEX idx_notification_deliveries_notification ON notification_deliveries (notification_id);
